version: 2
updates:
  # Keep Python dependencies up to date
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
